In [ ]:
# feature extractoring and preprocessing data
import librosa,librosa.display
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from PIL import Image
import csv

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, scale

#Keras
import keras
from keras import models
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.decomposition import PCA
#from keras.utils import to_categorical
from tensorflow.keras.utils import to_categorical
from keras.models import Sequential, Model, load_model
from keras.layers.normalization import BatchNormalization
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.optimizers import Adam
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from keras import optimizers
from keras.regularizers import l1
from keras.utils.vis_utils import plot_model
from sklearn import metrics
import pylab
plt.switch_backend('agg')
import itertools
import scipy as sp
from scipy import signal
import xgboost as xgb
import joblib
from glob import glob
import urllib


pd.plotting.register_matplotlib_converters()


#Loading CSV file
train_csv = pd.read_csv("/content/drive/MyDrive/CovidDataNew/cough_trial_extended.csv")
dataset = "/content/drive/MyDrive/CovidDataNew/data_new_extended.csv"

data = pd.read_csv("/content/drive/MyDrive/CovidDataNew/data_new_extended.csv")

data = data.drop(['filename'],axis=1)

genre_list = data.iloc[:, -1]
encoder = LabelEncoder()
y = encoder.fit_transform(genre_list)

scaler = StandardScaler()
X = scaler.fit_transform(np.array(data.iloc[:, :-1], dtype = float))

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

from sklearn.svm import SVC
classifier = SVC(kernel='linear', random_state = 1)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 6  0]
 [ 2 49]]


In [ ]:
x = cm[0,0] + cm[0,1] + cm[1,0] +cm[1,1]
y = cm[0,0] + cm[1,1]
z = y / x 
print('test_acc: ',z)

test_acc:  0.9649122807017544


In [ ]:
data = pd.read_csv("/content/drive/MyDrive/CovidDataNew/data_new_extended.csv")

In [ ]:
data

filename  chroma_stft      rmse  ...    mfcc19    mfcc20      label
0    0v8MGxNetjg_     0.519951  0.045853  ... -2.106427 -4.026825  not_covid
1    1j1duoxdxBg_     0.535472  0.001771  ...  2.781968  2.195162  not_covid
2    1MSYO4wgiag_     0.496666  0.033657  ... -1.118562 -5.906227  not_covid
3    1PajbAKd8Kg_     0.407549  0.013452  ... -4.772599 -0.503851  not_covid
4            cov1     0.412697  0.059004  ... -3.684266 -3.564146      covid
..            ...          ...       ...  ...       ...       ...        ...
165        #NAME?     0.492974  0.005093  ... -5.352920 -1.281080  not_covid
166        #NAME?     0.400283  0.052132  ... -8.422812 -0.831208  not_covid
167        #NAME?     0.704281  0.058739  ... -4.655417 -0.645009  not_covid
168        #NAME?     0.424896  0.044159  ... -8.861262 -5.078876  not_covid
169        #NAME?     0.434573  0.104041  ...  0.560492 -1.245852  not_covid

[170 rows x 28 columns]

In [ ]:
from sklearn.model_selection import KFold # import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [ ]:
kf = KFold(n_splits=10)  
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator

KFold(n_splits=10, random_state=None, shuffle=False)

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_test)
    print(confusion_matrix(y_test, y_pred))
    print(accuracy_score(y_test, y_pred))

[[9 4]
 [0 4]]
0.7647058823529411
[[ 5  1]
 [ 0 11]]
0.9411764705882353
[[17]]
1.0
[[17]]
1.0
[[17]]
1.0
[[ 0  0]
 [ 1 16]]
0.9411764705882353
[[ 0  0]
 [ 1 16]]
0.9411764705882353
[[17]]
1.0
[[17]]
1.0
[[17]]
1.0


In [ ]:
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.871, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.871, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.871, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.900, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.867, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.871, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.968, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=0.933, total=   0.0s
[CV] C=10, gamma=0.01, kernel=rbf ....................................
[CV] ........ C=10, gamma=0.01, kernel=rbf, score=1.000, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.903, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.935, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.871, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] ....... C=10, gamma=0.001, kernel=rbf, score=0.900, total=   0.0s
[CV] C=10, gamma=0.001, kernel=rbf ...................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    0.4s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [ ]:
# print best parameter after tuning
print(grid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(grid.best_estimator_)

{'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [ ]:
grid_predictions = grid.predict(X_test)
  # print classification report
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        17

    accuracy                           1.00        17
   macro avg       1.00      1.00      1.00        17
weighted avg       1.00      1.00      1.00        17

